#!/usr/bin/env python3
"""Build the local-only, DRAFT design review page from actual check results."""
import hashlib
import json
from build_manuscript import ROOT, page, section, table, link


def main():
    base=ROOT/"cad/table-node-pair_local-check"
    report=json.loads((base/"report.json").read_text())
    assert report["feature_script_sha256"]==hashlib.sha256((ROOT/"cad/table-node-pair_v0.1.fs").read_bytes()).hexdigest()
    body=section("boundary","这次推进到哪里",'<div class="reading-note"><p>两套本地三件实体已完成独立数字检查；下面是本地重建的模型与渲染，不是 Onshape 导出，也不是打印实物。FeatureScript 尚待云端编译，状态保持 DRAFT。</p><p>指定文件夹可写，但免费账户拒绝创建私有文档。公开保存须另经用户同意；本页不代表已经发布到 Onshape。</p></div>')
    toc=[("boundary","进度与边界")]
    for slug,title in [("clamp-tenon","夹头 · 水平槽底"),("shouldered-tenon","插肩 · 双斜肩教学变体")]:
        node=report["nodes"][slug]
        stem="table-node-pair_local-check/"+slug
        for suffix in ["_preview.glb","_assembled.webp","_exploded.webp"]:
            assert (ROOT/"cad"/(stem+suffix)).is_file()
        view=f'''<figure class="node-preview"><model-viewer id="{slug}-viewer" src="{stem}_preview.glb" poster="{stem}_exploded.webp" alt="{title}三件节点，本地设计预览" camera-controls interaction-prompt="none" animation-name="Explode" camera-orbit="38deg 66deg 0.42m" camera-target="0m 0.008m 0m" shadow-intensity="0.6"></model-viewer><label>拆装进度 <input type="range" min="0" max="1000" value="1000" step="1" data-viewer="{slug}-viewer" disabled></label><figcaption>拖动旋转；滑杆左端装合、右端拆开。拆卸先抬面板，再抬牙条。绿灰：面板；金黄：牙条；赭红：腿。</figcaption></figure><div class="node-images"><figure><img src="{stem}_assembled.webp" alt="{title}装合状态渲染"><figcaption>装合 · 数字渲染</figcaption></figure><figure><img src="{stem}_exploded.webp" alt="{title}拆分状态渲染"><figcaption>拆分 · 数字渲染</figcaption></figure></div>'''
        rows=[[name,f'{part["volume_mm3"]:.3f}',"1",str(part["triangle_count"]),"水密 / 绕向一致"] for name,part in node["parts"].items()]
        view+=table(["零件","体积 mm³","实体数","网格三角形","本地检查"],rows)
        rows=[[f['interface'],', '.join(f'{v:.6f}' for v in f['normal']),f'{f["area_mm2"]:.3f}'] for f in node['leg_bearing_planes']]
        view+=table(["腿上承托面","向外单位法线（X,Y,Z）","平面面积 mm²"],rows)
        view+='<p>面积来自本地 BREP 面。夹头槽底包括两侧间隙对应的窄条，整个槽底面积不等于与牙条实际重合的名义接触面积；插肩两面分别列出，不由面积推导强度。</p>'
        rows=[[name,str(m["samples"]),str(m["sample_step_mm"]),f'{m["max_intersection_mm3"]:.6f}',f'{m["negative_control_intersection_mm3"]:.3f}'] for name,m in node["motion"].items()]
        view+=table(["移动件","采样位置数","步长 mm","最大相交体积 mm³","越位 0.5 mm 相交体积"],rows)
        view+='<p>最终装合三对零件的相交体积均为 0；接触终点的最小间隔为 0。采样不等于连续扫掠证明，越位负对照只检查止挡存在，不证明承载能力。</p>'
        body+=section(slug,title,view)
        toc.append((slug,title))
    body+=section("parameters","共用尺寸与差异",table(["对象","本轮值","边界"],[
        ["腿 / 牙条 / 面板","24×24×96 / 96×8×24 / 96×40×16 mm","单节点，不是完整桌架"],
        ["双顶榫","各 16×2×8 mm","薄榫未经强度验证"],
        ["顶榫配合 / 避底","总间隙 0.30 / 端部 0.40 mm","本轮试验值，不推荐打印参数"],
        ["夹头槽","宽 8.30 mm；槽底 Z=-24 mm","水平面止挡"],
        ["插肩槽","上宽 16、下宽 8、高 24 mm；相对竖直 9.4623°","斜面名义接触；槽底再让 0.40 mm"],
        ["装配动作","牙条 −Z 48 mm → 面板 −Z 96 mm","腿固定，先牙条后面板"]]))
    toc.append(("parameters","尺寸与差异"))
    body+=section("source","文件与下一步",'<div class="reading-links">'+link("参数化 FeatureScript →","table-node-pair_v0.1.fs")+link("工作记录与简化边界 →","table-node-pair_v0.1.md")+link("机器可读检查报告 →","table-node-pair_local-check/report.json")+'</div><p>下一步：获准保存方式后，在 Onshape 编译、读回三实体、补稳定接触面标注与非空总装，冻结版本并同源导出；之后才进入打印实验。现有本地 STEP / STL 是检查中间件，不是正式打印包。Gate A 与作品级 S2 仍未通过。</p>')
    toc.append(("source","源与下一步"))
    result=page("夹头 / 插肩 · CAD 对照审阅","同尺度三件节点，把水平槽底和双斜肩的停止位置分别落实为几何。","Local CAD design review · v0.1","DRAFT · 本地数字检查 · 云端未编译 · 未试打",body,toc)
    result=result.replace('<!-- Generated by tools/build_manuscript.py. Edit content/manuscript_v0.1.json or content/teaching_spec_v0.1.json. -->','<!-- Generated by tools/build_table_nodes_review.py from actual local check results. -->').replace('2026-09-08','2026-09-12').replace('正文初稿 v0.1','CAD 工作稿 v0.1')
    result=result.replace('</head>','''<style>.node-preview model-viewer{display:block;width:100%;height:470px;background:#eeeae1}.node-preview label{display:flex;gap:16px;align-items:center;padding:15px 0}.node-preview input{flex:1}.node-preview figcaption,.node-images figcaption{font-size:13px;color:#777}.node-images{display:grid;grid-template-columns:1fr 1fr;gap:12px}.node-images figure,.node-preview{margin:20px 0}.node-images img{width:100%;display:block}@media(max-width:600px){.node-preview model-viewer{height:350px}.node-images{grid-template-columns:1fr}}</style></head>''')
    result=result.replace('</body>','''<script type="module" src="../assets/vendor/model-viewer-4.3.1.min.js"></script><script>
document.querySelectorAll('[data-viewer]').forEach(range=>{
  const viewer=document.getElementById(range.dataset.viewer);
  const caption=viewer.parentElement.querySelector('figcaption');
  if(location.protocol==='file:')caption.textContent='交互 3D 需通过本地 HTTP 打开：运行 npm run dev，访问 /cad/table-node-pair.html。下方静态渲染可直接查看。';
  const update=()=>{viewer.currentTime=Math.min(Number(range.value)/1000*viewer.duration,viewer.duration-0.001);};
  viewer.addEventListener('load',()=>{viewer.play();viewer.pause();range.disabled=false;update();});
  viewer.addEventListener('error',()=>{caption.textContent='3D 载入失败，请通过本地 HTTP 打开；下方静态图仍可审阅。';});
  range.addEventListener('input',update);
});
</script></body>''')
    (ROOT/"cad/table-node-pair.html").write_text(result)
    print("Built cad/table-node-pair.html from checked local geometry")


if __name__=="__main__":main()
