#!/usr/bin/env python3
"""Build static reading chapters from authored content; --check detects drift.

This produces prose pages, not geometry releases. It never edits manifests,
credentials, CAD, author decisions, or the existing four case chapters.
"""
from __future__ import annotations

import argparse
import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def esc(value: object) -> str:
    return html.escape(str(value), quote=True)


def read(name: str) -> dict:
    return json.loads((ROOT / "content" / name).read_text(encoding="utf-8"))


def link(label: str, path: str) -> str:
    return f'<a href="{esc(path)}">{esc(label)}</a>'


def paragraphs(items: list[str]) -> str:
    return "\n".join(f"<p>{esc(item)}</p>" for item in items)


def table(headers: list[str], rows: list[list[str]]) -> str:
    head = "".join(f'<th scope="col">{esc(h)}</th>' for h in headers)
    body = "\n".join("<tr>" + "".join(f"<td>{esc(c)}</td>" for c in row) + "</tr>" for row in rows)
    return f'<div class="reading-table" tabindex="0" role="region" aria-label="{esc(headers[0])}表，可横向滚动"><table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table></div>'


def section(anchor: str, title: str, body: str) -> str:
    return f'<section id="{esc(anchor)}"><h2>{esc(title)}</h2>\n{body}\n</section>'


def page(title: str, deck: str, kicker: str, status: str, body: str,
         toc: list[tuple[str, str]], prefix: str = "../") -> str:
    nav = "".join(link(t, prefix + p) for t, p in [
        ("阅读目录", "book.html"), ("公共参数", "cad/teaching-spec.html"),
        ("10+3 工作台", "first-wave.html"), ("路线图", "joinery_book_roadmap.html")])
    contents = "".join(link(t, "#" + a) for a, t in toc)
    return f'''<!doctype html>
<!-- Generated by tools/build_manuscript.py. Edit content/manuscript_v0.1.json or content/teaching_spec_v0.1.json. -->
<html lang="zh-CN">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{esc(title)} · 可打印的榫卯</title><meta name="description" content="{esc(deck)}">
<link rel="icon" href="data:,"><link rel="stylesheet" href="{prefix}assets/styles.css"><link rel="stylesheet" href="{prefix}assets/manuscript.css"></head>
<body><a class="skip-reading" href="#reading">跳至正文</a><div class="reading-shell">
<nav class="reading-nav" aria-label="全书导航">{link('可打印的榫卯', prefix + 'index.html')}<div>{nav}</div></nav>
<header class="reading-hero"><div class="kicker">{esc(kicker)}</div><h1>{esc(title)}</h1><p class="reading-deck">{esc(deck)}</p>
<div class="reading-status"><span>正文初稿 v0.1</span><span class="draft">{esc(status)}</span><span>2026-09-08</span></div></header>
<div class="reading-layout"><main id="reading" class="reading-body">{body}</main><aside class="reading-toc" aria-label="本页目录"><strong>本页阅读</strong>{contents}</aside></div>
<footer class="reading-footer">Printable Joinery Atlas · 首批正文 v0.1 · 网页正文可独立阅读和打印；概念图不替代 CAD 或实物证据。</footer>
</div></body></html>
'''


def figure(kind: str, caption: str, steps: list[dict]) -> str:
    if kind == "sequence":
        drawing = '<div class="reading-flow">' + "".join(
            f'<div><span>候选步骤 {esc(s["step"])}</span><b>{esc(s["title"])}</b><small>{esc(s["watch"])}</small></div>' for s in steps) + '</div>'
    else:
        # Abstract explanatory drawings, deliberately not CAD-derived shapes.
        drawings = {
            "contacts": '''<rect x="70" y="28" width="480" height="55" rx="6" fill="#d7a56e" stroke="#171816" stroke-width="2"/>
<text x="310" y="63" text-anchor="middle">上部件 · IF-TOP · 顶榫侧壁与肩面</text>
<path d="M205 88v60m210-60v60" stroke="#b96042" stroke-width="3" stroke-dasharray="6 5"/>
<rect x="100" y="153" width="210" height="72" rx="6" fill="#eeeae0" stroke="#171816" stroke-width="2"/><text x="205" y="195" text-anchor="middle">腿足 · 共同基准</text>
<rect x="355" y="153" width="200" height="72" rx="6" fill="#d8c8af" stroke="#171816" stroke-width="2"/><text x="455" y="195" text-anchor="middle">牙条 · IF-APRON</text>
<path d="M315 188h34" stroke="#b96042" stroke-width="3"/>
<text x="310" y="268" text-anchor="middle">定位 FIT / 止位 STOP / 避让 CLEAR 分别定义</text>''',
            "pin": '''<rect x="45" y="40" width="530" height="170" rx="9" fill="#eeeae0" stroke="#171816" stroke-width="2"/>
<path d="M75 65h100v45h350v35H175v40H75z" fill="#fbfaf7" stroke="#171816" stroke-width="2"/>
<circle cx="125" cy="126" r="34" fill="#d7a56e" stroke="#171816" stroke-width="2"/>
<circle cx="470" cy="127" r="34" fill="none" stroke="#b96042" stroke-width="3" stroke-dasharray="6 5"/>
<circle cx="470" cy="127" r="12" fill="#b96042"/>
<path d="M225 127h170l-13-8m13 8-13 8" fill="none" stroke="#171816" stroke-width="2"/>
<text x="125" y="246" text-anchor="middle">1 · 销头进入宽口</text><text x="464" y="246" text-anchor="middle">2 · 销根滑入窄槽</text>
<text x="310" y="280" text-anchor="middle">拆卸：先滑回入口，再沿法向退出</text>''',
            "lap": '''<path d="M35 150h550" stroke="#536b7a" stroke-width="2" stroke-dasharray="5 5"/>
<rect x="48" y="95" width="145" height="55" fill="#eeeae0" stroke="#171816" stroke-width="2"/><rect x="88" y="64" width="63" height="70" fill="#d7a56e" stroke="#171816" stroke-width="2"/>
<rect x="238" y="95" width="145" height="55" fill="#eeeae0" stroke="#171816" stroke-width="2"/><rect x="278" y="80" width="63" height="70" fill="#d7a56e" stroke="#171816" stroke-width="2"/>
<rect x="428" y="95" width="145" height="55" fill="#eeeae0" stroke="#171816" stroke-width="2"/><rect x="468" y="96" width="63" height="70" fill="#d7a56e" stroke="#171816" stroke-width="2"/>
<text x="120" y="208" text-anchor="middle">浅槽 · B 抬高</text><text x="310" y="208" text-anchor="middle">基线 · 共面</text><text x="500" y="208" text-anchor="middle">深槽 · B 下沉</text>
<text x="120" y="238" text-anchor="middle">h = +0.2 mm</text><text x="310" y="238" text-anchor="middle">h = 0</text><text x="500" y="238" text-anchor="middle">h = −0.2 mm</text>
<text x="310" y="278" text-anchor="middle">自由落位、槽底接触；蓝虚线为 A 底面基准</text>''',
            "box": '''<rect x="150" y="42" width="320" height="220" fill="#d7a56e" stroke="#171816" stroke-width="2"/>
<rect x="166" y="58" width="288" height="188" fill="#fbfaf7" stroke="#171816" stroke-width="2"/>
<path d="M150 24h320m-320-5v10m320-10v10M492 42v220m-5-220h10m-10 220h10" stroke="#536b7a" stroke-width="2"/>
<text x="310" y="18" text-anchor="middle">160 mm · X</text><text x="510" y="148">110 mm</text>
<text x="310" y="137" text-anchor="middle">内净空 144×94 mm</text><text x="310" y="165" text-anchor="middle">底板伸入槽内，尺寸另算</text>
<text x="310" y="290" text-anchor="middle">壁厚 8 mm · 高 70 mm · 角部拓扑待 CAD</text>'''
        }
        drawing = f'<svg viewBox="0 0 620 310" role="img" aria-label="{esc(caption)}"><title>{esc(caption)}</title>{drawings[kind]}</svg>'
    return f'<figure class="reading-figure">{drawing}<figcaption>图解 · {esc(caption)}</figcaption></figure>'


def generate() -> dict[str, str]:
    wave = read("first_wave_v0.1.json")
    manuscript = read("manuscript_v0.1.json")
    spec = read("teaching_spec_v0.1.json")
    entries = {e["id"]: e for e in wave["joints"] + wave["works"]}
    authored = {c["id"]: c for c in manuscript["chapters"]}
    assert len(authored) == len(manuscript["chapters"]) == 9
    paths = {e["id"]: e.get("chapter_path") or e.get("case_path") or
             ("joints/" if e in wave["joints"] else "works/") + e["id"] + ".html" for e in entries.values()}
    output = {}
    for slug, c in authored.items():
        e = entries[slug]
        local_cad = e.get("local_cad_review")
        title = e["name_cn"]
        toc = [("opening", "读懂问题")]
        body = section("opening", c["deck"], f'<p class="reading-intro">{esc(c["intro"])}</p>')
        citations = " · ".join(link(wave["sources"][s]["title"], wave["sources"][s]["url"]) for s in c["source_ids"])
        body += f'<div class="reading-note"><p>{esc(c["source_note"])}</p><p>结构来源：{citations}</p></div>'
        body += figure(c["drawing"]["type"], c["drawing"]["caption"], e["assembly_steps"])
        for number, s in enumerate(c["sections"], 1):
            anchor = f"section-{number}"
            body += section(anchor, s["title"], paragraphs(s["paragraphs"]))
            toc.append((anchor, s["title"]))
        body += section("parameters", "把关系写成参数", '<p>以下数值是教学设计起点或明确限定的算例。没有实测的字段仍待指定，不能当作推荐打印参数。</p>' + table(["对象", "定义 / 关系", "适用边界"], c["relations"]) +
                        link("完整公共参数规范 →", "../cad/teaching-spec.html"))
        toc.append(("parameters", "参数与约束"))
        rows = [[s["step"] + " · " + s["title"], s["action"], s["watch"]] for s in e["assembly_steps"]]
        assembly_note = '下表保留设计阶段的观察任务。FreeCAD 教学母版已完成 1 mm 步长装配采样，摘要与限制见章末 CAD 对照审阅；完整母版与交互预览留在本地，尚非实物装配教程。' if local_cad else '这是下一轮 CAD 要验证的步骤，尚非经验证的装配教程；上文指出的路径冲突与变形问题仍须解决。'
        body += section("assembly", "候选装配与观察记录", '<p>' + assembly_note + '</p>' + table(["步骤", "候选动作", "重点检查"], rows))
        toc.append(("assembly", "候选装配"))
        body += section("failures", "遇到异常，先定位原因", table(["观察到什么", "待核查原因", "如何记录"], c["failure_reading"]) + f'<div class="reading-exercise"><strong>读者练习</strong><p>{esc(c["exercise"])}</p></div>')
        toc.append(("failures", "异常与练习"))
        debt = "".join(f'<li>{esc(d)}</li>' for d in e["experiment_debt"])
        deliverables = "".join(f'<li>{esc(d)}</li>' for d in e["cad_deliverables"])
        evidence = ('<p>已完成 FreeCAD 原生参数化母版、改参重算和同源几何检查；母版及精确派生文件留在本地，Onshape 仅可选同步。没有实物验证，状态保持 DRAFT，Gate A 未通过。</p><p>' + link("查看同尺度静态 CAD 对照与检查摘要 →", "../" + local_cad) + '</p>') if local_cad else '<p>已完成本章正文与设计约束；尚无本章新增 CAD、可下载几何或实物验证。编辑进度为 IMPLEMENTED（页面已存在），不代表资产证据升级。Gate A 保持未通过。</p>'
        body += section("evidence", "本章做到哪里", evidence +
                        f'<h3>{"CAD 与图稿交付清单（已完成项见审阅页）" if local_cad else "待补的 CAD 与图稿"}</h3><ul>{deliverables}</ul><h3>后续实验问题</h3><ul>{debt}</ul>' +
                        '<p>配合记录沿用 ' + link("Clearance Lab", "../labs/clearance.html") + ' 的字段与版本追溯原则；其他结构需扩展其专属测量项，不能直接套用直榫结果。</p>')
        toc.append(("evidence", "证据与下一步"))
        body += '<div class="reading-links">' + "".join(link(entries[n]["name_cn"] + " →", "../" + paths[n]) for n in c["next_ids"]) + '</div>'
        output[paths[slug]] = page(title, c["deck"], e["index"] + " · " + e["name_en"], "DRAFT · FreeCAD 本地母版 · 未经实物验证" if local_cad else "设计正文 · CAD 待实现 · 未经实物验证", body, toc)

    # The reading index includes the three existing joint chapters and Baxian case.
    cards = {}
    for kind, label in [("joints", "十个基本榫卯"), ("works", "三个综合作品")]:
        items = []
        for e in wave[kind]:
            new = e["id"] in authored
            state = "正文初稿 · FreeCAD 本地母版已检查" if e.get("local_cad_review") else "正文初稿 · CAD 待实现" if new else e["evidence_state"]
            items.append(f'<a class="reading-card" href="{paths[e["id"]]}"><small>{esc(e["index"])} · {"新增正文" if new else "既有章节"}</small><h3>{esc(e["name_cn"])}</h3><p>{esc(e["one_sentence"])}</p><span>{esc(state)}</span></a>')
        cards[kind] = section(kind, label, '<div class="reading-card-grid">' + "".join(items) + '</div>')
    body = section("start", "从局部配合，读到完整作品", paragraphs([
        "这轮把七份榫卯简报与两份作品简报扩写为独立正文，并与原有直榫、燕尾榫、楔钉榫和八仙桌章节连接起来。先读几何允许怎样运动，再读参数怎样定义，最后看已有证据和待验证问题。",
        "阅读顺序可以按对照关系选择：夹头与插肩比较接触面；十字半搭接与粽角比较材料让位；走马销与破头楔比较退出路径和变形。两个新作品把这些问题放进闭环。全书其余 14 个榫卯与 3 个作品仍保留为后续轮次。"
    ]) + '<div class="reading-note">13 个首批条目均有阅读页面，不等于 13 套 CAD 或验证打印包。新增九章为设计正文初稿，路径示意、公式算例与历史来源分别标注。</div>' +
        '<div class="reading-links">' + link("先读统一教学参数 →", "cad/teaching-spec.html") + link("回到 24+6 全书目录 →", "design-catalog.html") + '</div>')
    body += cards["joints"] + cards["works"]
    output["book.html"] = page("可打印的榫卯 · 首批正文", "十个基本榫卯，三个综合作品。把结构关系、装配问题和证据边界写成可以连续阅读的章节。", "Reading edition · first wave 10 + 3", "13 个阅读入口 · 新增 9 篇正文", body,
                              [("start", "怎样阅读"), ("joints", "10 个基本榫卯"), ("works", "3 个综合作品")], "")

    # The displayed spec is generated from the same values a CAD author consumes.
    body = section("scope", "冻结的是接口，不是推荐值", paragraphs([spec["scope"], spec["clearance_policy"], "本规范先让十种结构能在同一套术语下比较。外廓和展示段给出本项目设计起点，局部榫区、强度、装配可行性仍由对应 CAD 与实验确认。旧模型不因新母尺寸发布而重缩放。"])); toc = [("scope", "范围")]
    body += section("profiles", "统一教学尺度", table(["组别", "适用条目", "尺寸与边界"], [[p["id"] + " · " + p["label"], " / ".join(entries[n]["name_cn"] for n in p["applies_to"]), p["note"]] for p in spec["profiles"]]) + table(["作品", "外廓 mm", "已确认边界"], [[entries[w["id"]]["name_cn"], " × ".join(map(str, w["dimensions_mm"])) if w["dimensions_mm"] else "保留源 CAD", w["note"]] for w in spec["work_envelopes"]])); toc.append(("profiles", "教学尺度"))
    body += section("fields", "总间隙、单面距离与局部让位", table(["字段 / 符号", "默认值", "定义"], [[f["id"] + " / " + f["symbol"], "待指定（null）" if f["default"] is None else str(f["default"]) + " " + f["unit"], f["definition"]] for f in spec["fields"]])); toc.append(("fields", "配合字段"))
    coord = spec["coordinate_system"]
    body += section("frames", "坐标与接触面", table(["基准", "定义"], [["单位", "长度 mm；角度 deg；体积 mm³"], ["坐标手性", "右手系"], ["X", coord["x"]], ["Y", coord["y"]], ["Z", coord["z"]], ["原点", coord["origin"]], ["打印坐标", coord["print_frame"]]]) + table(["接口", "职责", "约定"], [[i["id"] + " · " + i["meaning"], i["classification"], i["rule"]] for i in spec["interfaces"]])); toc.append(("frames", "坐标与接口"))
    body += section("exports", "从一个源身份派生输出", '<ol>' + "".join(f'<li>{esc(r)}</li>' for r in spec["export_rules"]) + '</ol>' + '<p>glTF 单位与轴向依据 ' + link("Khronos glTF 2.0 Specification · Coordinate System and Units", "https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#coordinate-system-and-units") + '；项目资产身份与证据规则见 ' + link("ASSET_CONTRACT.md", "../ASSET_CONTRACT.md") + '。</p>'); toc.append(("exports", "派生输出"))
    body += section("handoff", "首批 CAD 的明确交接点", paragraphs(["夹头 / 插肩共用 N24 外廓，分别记录 IF-TOP 与 IF-APRON；两套 FreeCAD 原生母版已完成数字检查。粽角要先证明最后一件的进入路径；收纳盒要解决末边两角与底槽的运动冲突；小案要解决两向牙条在腿顶的占材与闭环。", "2026-09-12 用户确认后续以 FreeCAD 本地母版为准，Onshape 仅可选同步；原生文件、精确派生件和详细参数默认不上传公共仓库。旧有 Onshape 资产保持原来源记录。破头楔的刚体进入段与受迫变形段仍须分别记录。"])+ '<div class="reading-links">' + link("机器可读参数 JSON →", "../content/teaching_spec_v0.1.json") + link("阅读首批正文 →", "../book.html") + '</div>'); toc.append(("handoff", "CAD 交接"))
    output["cad/teaching-spec.html"] = page("统一教学参数与输出约定", "十种结构共用一套尺寸语言；每张接触面都有职责，每次装配都有方向。", "Teaching specification · v0.1", "编辑接口已冻结 · 几何与打印待验证", body, toc)
    return output


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check generated pages without writing")
    args = parser.parse_args()
    output = generate()
    stale = []
    for relative, content in output.items():
        path = ROOT / relative
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(relative)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale:
        print("Stale manuscript pages: " + ", ".join(stale))
        return 1
    print(f"Manuscript {'checked' if args.check else 'built'}: 9 new chapters + reading index + teaching specification ({len(output)} static pages).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
