#!/usr/bin/env python3
"""Create the keyed-tenon (楔钉榫) teaching model in an empty Part Studio.

Geometry follows the CAD Spec v0.3 numbers published in cad/index.html: 24 x 18
mm stock, a 30 mm half-lap split 9 + 9, an 8 x 5 x 3 mm tongue at each lap end,
and a 7 mm square through-hole at the lap centre.

Decisions that table does not cover are recorded here:

* The tongue is a stub tenon projecting from the lap's end shoulder into a blind
  mortise in the other member, not a boss sitting on the lap face.  A boss would
  leave the members free to separate along Z; a stub tenon buried in the mating
  member's full section blocks Y and Z outright, which leaves the axial slide as
  the only remaining freedom.  That is what the key is there to lock, so the
  three features decompose the degrees of freedom without overlapping.
* Clearance is applied to fits and only to fits.  The tongue/mortise pair and
  the key hole each carry C = 0.20 mm; the lap face and the two 24 x 9 mm shoulders
  are left coincident because they are bearing surfaces -- clearing them would
  buy nothing and leave the assembled joint rattling in Z and X.
* What actually stops a printed lap from seating is not the face dimension but
  the concave root corners, where FDM leaves a nozzle radius and an elephant
  foot.  Those get explicit relief instead: a 0.4 mm chamfer at each lap corner
  and a 0.3 mm counterbore at each mortise mouth.  The dovetail model solves the
  same problem the same way.
* Every fit clearance is split evenly between the two parts, and member B is
  generated by mirroring member A's profiles through the 180 degree rotation
  about Y that maps one onto the other.  The joint therefore prints as one part
  twice, and both members' shoulder positions carry identical error, so both
  shoulders seat together instead of one fighting the other.
* The key and its hole taper at the same rate, so the key does not wedge; it
  grips over the full face like a Morse taper, and its seat depth is decided by
  size alone at 11.25 mm per mm of error.  The key drawn here is the one now in
  the workspace, redrawn by hand after v0.7's zero-clearance key printed too
  tight: 0.35 mm under the hole in X and 0.40 mm in Y.  That clearance is paid
  for in depth -- it sinks 3.94 mm and its tip leaves the far face by 3.77 mm.

Credentials are read from the environment so that .env is never embedded in the
model definition or emitted by this script.
"""

from __future__ import annotations

import argparse
import base64
import json
import os
import sys
import urllib.error
import urllib.request


DID = "73de9c93248e073d85379a97"
WID = "1bd7eba357dd91d2503bfa3c"
EID = "bd84c453f68419d4085d9688"
FEATURES_PATH = f"/api/v10/partstudios/d/{DID}/w/{WID}/e/{EID}/features"

# ---------------------------------------------------------------------------
# Parameters, in millimetres.  Sketch coordinates are converted to metres on the
# way out because Onshape serializes sketch geometry in SI units.
# ---------------------------------------------------------------------------
WIDTH = 24.0            # stock width, along Y
HEIGHT = 18.0           # stock height, along Z
OVERLAP = 30.0          # half-lap length, along X, centred on the origin
HALF_LAP = 9.0          # each member keeps this much of the height in the lap
FREE_LENGTH = 35.0      # full-section run beyond the lap, per member

TONGUE_W, TONGUE_L, TONGUE_H = 8.0, 5.0, 3.0
TONGUE_C = 0.20         # total mother-minus-male difference, split evenly
TIP_GAP = 0.40          # deliberate non-bearing gap at the tongue tip

# FDM leaves a nozzle radius in every concave corner, and this joint has two
# places where such a corner faces a sharp one on the mating member: the lap
# corner, and the root of each tongue.  Left alone they hold the joint open, and
# because the assembly is over-constrained the resulting gap lands unpredictably
# on the lap face or on either shoulder.  Both reliefs are cuts at the corner
# rather than clearance on the face, so all three bearing surfaces still meet.
#
# Both are shaped in the Front sketch, which works because the members print on
# a side face: the build direction is then Y, layers are X-Z planes, and every
# concave corner that matters lies in that plane.  That orientation also keeps
# the tongue from being a 5 mm unsupported overhang, which it would be if the
# member were printed lying on its 24 x 70 footprint.
# CORNER_RELIEF is an assumption, not a derivation.  It was once justified by
# "a fillet of radius r intrudes only 0.414 r along the diagonal, so c >= 0.586 r
# suffices", but the diagonal is where such a fillet intrudes least: it reaches a
# full r along each wall.  Keeping the same nozzle-radius model and asking
# instead where the relief's own concave vertex lands gives c >= (1 + sqrt 2) r,
# about 0.48 mm for a 0.4 mm nozzle -- which makes 0.20 mm a notch narrower than
# the nozzle meant to cut it, so the first print may show no relief at all.
# The value is left as built so the part matches the frozen v0.7; the print,
# not another derivation, is what should move it.
#
# The lap corner is on the outside of the assembled joint, so a relief taken
# across the full 24 mm width breaks out on both side faces and leaves a notch
# in the seam -- four of them on the finished piece.  This one therefore stops
# short of both side faces: it is cut as its own feature over the middle
# 23 mm, leaving 0.5 mm of sharp corner at each edge so the seam reads as one
# continuous line.  Those two slivers keep about 0.08 mm of interference, on the
# most compliant part of the section; that is the price of an unbroken seam.
#
# The mortise mouth has no such constraint.  It sits inside the shoulder face,
# hidden once assembled, so it stays in the pocket profile with a generous
# lead-in that also helps the tongue start.
CORNER_RELIEF = 0.20    # 45 deg relief across each concave lap corner
CORNER_EDGE_KEEP = 0.50 # left sharp at each side face so the seam stays closed
MOUTH_CHAMFER = 0.50    # 45 deg lead-in at each mortise mouth, in Z

# --- key and hole ----------------------------------------------------------
# The key is a flat wedge: it tapers in X only, so its two Y faces stay parallel.
# That lets it print lying on a face with the layers running along the shear
# path, and it turns what used to be knife-edge contact at the hole mouth into
# full-face contact down both X walls.
#
# The hole and the key taper at very nearly the same rate, and that is the whole
# story of how this key behaves.  Two matched tapers do not wedge in the usual
# sense -- there is no angle between the faces for the key to drive itself into.
# They grip the way a Morse taper grips, by friction over the full face, and the
# depth at which that grip starts is set entirely by size.  So a wedge cannot be
# flush, tight and clearanced at once: clearance always buys depth instead.
#
# v0.7 spent nothing on clearance in X.  The key was the hole's own profile over
# its top 13.5 mm -- 6.80 -> 8.00 mm, 7.00 mm thick -- so it seated with its head
# flush and its tip 4.50 mm above the far face.  It printed too tight to press in
# by hand, so the workspace key was redrawn afterwards, by hand, in the Onshape
# sketch: 6.05 -> 7.65 mm over 17.83125 mm and 6.80 mm thick.  These numbers are
# read back from the live workspace rather than chosen here; the sketch carries no
# dimensions, which is why KEY_LENGTH is not a round figure.
#
# What that clearance bought is depth, exactly as above.  The key is now 0.35 mm
# under the hole in X at every level and 0.40 mm under it in Y, so it sinks
# KEY_SINK before its head catches the wall, and its tip comes out the far side
# by KEY_PROTRUSION.  It is easy to press in and it no longer lands flush.
HOLE_Y = 7.20           # constant across the depth: nominal 7 plus C = 0.20
HOLE_X_BOTTOM = 6.40
HOLE_X_TOP = 8.00
HOLE_TAPER = (HOLE_X_TOP - HOLE_X_BOTTOM) / HEIGHT   # 0.08889, X per mm of depth
KEY_Y = 6.80            # 0.40 mm under the hole's 7.20
KEY_X_TIP = 6.05
KEY_X_HEAD = 7.65
KEY_LENGTH = 17.83125   # measured off the workspace sketch, not dimensioned in it
KEY_TAPER = (KEY_X_HEAD - KEY_X_TIP) / KEY_LENGTH    # 0.08973, 1% over the hole's
KEY_PARK_X = 80.355     # the key is modelled beside the joint, not inserted
KEY_PARK_Z = 0.0

# KEY_TAPER exceeds HOLE_TAPER, so the key catches at its head rather than its
# tip: the head is KEY_X_HEAD wide and stops where the hole has narrowed to that.
# (Over the key's whole length the two tapers differ by 0.015 mm, which is less
# than one extrusion width -- so on a printed part this is a matched taper.)
KEY_SINK = (HOLE_X_TOP - KEY_X_HEAD) / HOLE_TAPER       # 3.94, head below entry
KEY_PROTRUSION = KEY_LENGTH + KEY_SINK - HEIGHT         # 3.77, tip past far face

HALF = OVERLAP / 2                       # 15.0
LAP_END = HALF                           # A's lap ends here; B's full section starts
MAIN_END = HALF + FREE_LENGTH            # 50.0
TONGUE_TIP = HALF + TONGUE_L             # 20.0
MORTISE_BOTTOM = HALF + TONGUE_L + TIP_GAP  # 20.4

# TONGUE_C is the total mother-minus-male difference.  Half of it comes off the
# tongue and half is added to the mortise, which is what keeps the two members
# congruent; taking it all out of the mortise would not.
SPLIT = TONGUE_C / 2                     # 0.10, applied to each part
TONGUE_HW = (TONGUE_W - SPLIT) / 2       # 3.95
MORTISE_HW = (TONGUE_W + SPLIT) / 2      # 4.05
TONGUE_MID = HALF_LAP / 2                # tongue centred in the 9 mm lap
TONGUE_LO = TONGUE_MID - (TONGUE_H - SPLIT) / 2   # 3.05
TONGUE_HI = TONGUE_MID + (TONGUE_H - SPLIT) / 2   # 5.95
MORTISE_LO = TONGUE_MID - (TONGUE_H + SPLIT) / 2  # 2.95
MORTISE_HI = TONGUE_MID + (TONGUE_H + SPLIT) / 2  # 6.05



def request(method: str, path: str, payload: dict | None = None) -> dict:
    key = os.environ["ONSHAPE_ACCESS_KEY"]
    secret = os.environ["ONSHAPE_SECRET_KEY"]
    base_url = os.environ.get("ONSHAPE_BASE_URL", "https://cad.onshape.com").rstrip("/")
    headers = {
        "Accept": "application/json;charset=UTF-8; qs=0.09",
        "Authorization": "Basic " + base64.b64encode(f"{key}:{secret}".encode()).decode(),
    }
    body = None
    if payload is not None:
        body = json.dumps(payload).encode()
        headers["Content-Type"] = "application/json;charset=UTF-8; qs=0.09"
    req = urllib.request.Request(base_url + path, data=body, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=90) as response:
            raw = response.read()
            return json.loads(raw) if raw else {}
    except urllib.error.HTTPError as error:
        detail = error.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"Onshape returned HTTP {error.code}: {detail}") from error


def plane_parameter(plane_name: str) -> dict:
    return {
        "btType": "BTMParameterQueryList-148",
        "parameterId": "sketchPlane",
        "queries": [
            {
                "btType": "BTMIndividualQuery-138",
                "queryString": f'query=qCreatedBy(makeId("{plane_name}"), EntityType.FACE);',
            }
        ],
    }


def line(entity_id: str, start: tuple[float, float], end: tuple[float, float]) -> dict:
    dx, dy = end[0] - start[0], end[1] - start[1]
    length = (dx * dx + dy * dy) ** 0.5
    return {
        "btType": "BTMSketchCurveSegment-155",
        "entityId": entity_id,
        "startPointId": f"{entity_id}.start",
        "endPointId": f"{entity_id}.end",
        "isConstruction": False,
        "startParam": 0.0,
        "endParam": length,
        "geometry": {
            "btType": "BTCurveGeometryLine-117",
            "pntX": start[0],
            "pntY": start[1],
            "dirX": dx / length,
            "dirY": dy / length,
        },
    }


def profile_sketch(name: str, plane_name: str, points_mm: list[tuple[float, float]]) -> dict:
    points = [(u / 1000.0, v / 1000.0) for u, v in points_mm]
    entities = [
        line(f"edge_{index + 1}", point, points[(index + 1) % len(points)])
        for index, point in enumerate(points)
    ]
    return {
        "btType": "BTFeatureDefinitionCall-1406",
        "feature": {
            "btType": "BTMSketch-151",
            "featureType": "newSketch",
            "name": name,
            "parameters": [plane_parameter(plane_name)],
            "entities": entities,
            "constraints": [],
            "suppressed": False,
            "returnAfterSubfeatures": False,
        },
    }


def multi_loop_sketch(name: str, plane_name: str,
                      loops: list[list[tuple[float, float]]]) -> dict:
    """Several closed loops in one sketch, so one extrude can consume them all."""
    entities = []
    for index, loop in enumerate(loops):
        points = [(u / 1000.0, v / 1000.0) for u, v in loop]
        for edge, point in enumerate(points):
            entities.append(line(f"loop{index}_edge{edge}", point,
                                 points[(edge + 1) % len(points)]))
    return {
        "btType": "BTFeatureDefinitionCall-1406",
        "feature": {
            "btType": "BTMSketch-151", "featureType": "newSketch", "name": name,
            "parameters": [plane_parameter(plane_name)], "entities": entities,
            "constraints": [], "suppressed": False, "returnAfterSubfeatures": False,
        },
    }


def rectangle(u0: float, u1: float, v0: float, v1: float) -> list[tuple[float, float]]:
    return [(u0, v0), (u1, v0), (u1, v1), (u0, v1)]


def mirror(points: list[tuple[float, float]]) -> list[tuple[float, float]]:
    """The 180 degree rotation about Y that carries member A onto member B.

    It is a rotation, not a reflection, so the sketch winding survives it.  Every
    one of B's profiles is generated this way rather than typed out again, which
    is what makes the congruence a property of the model instead of a promise.
    """
    return [(-u, HEIGHT - v) for u, v in points]


def extrude(name: str, sketch_id: str, operation: str, extra: list[dict]) -> dict:
    parameters = [
        {"btType": "BTMParameterEnum-145", "value": "SOLID",
         "enumName": "ExtendedToolBodyType", "parameterId": "bodyType"},
        {"btType": "BTMParameterEnum-145", "value": operation,
         "enumName": "NewBodyOperationType", "parameterId": "operationType"},
        {"btType": "BTMParameterQueryList-148", "parameterId": "entities",
         "queries": [{"btType": "BTMIndividualSketchRegionQuery-140", "featureId": sketch_id}]},
        # Every boolean in this model is meant to see the whole Part Studio; the
        # cuts are kept off the neighbouring body by where they sit, not by scope.
        {"btType": "BTMParameterBoolean-144", "value": True, "parameterId": "defaultScope"},
    ]
    return {
        "btType": "BTFeatureDefinitionCall-1406",
        "feature": {
            "btType": "BTMFeature-134",
            "featureType": "extrude",
            "name": name,
            "parameters": parameters + extra,
            "suppressed": False,
            "returnAfterSubfeatures": False,
        },
    }


def symmetric_blind(depth_mm: float) -> list[dict]:
    """Extrude the sketch evenly to both sides; `depth` is the total distance."""
    return [
        {"btType": "BTMParameterEnum-145", "value": "BLIND",
         "enumName": "BoundingType", "parameterId": "endBound"},
        {"btType": "BTMParameterQuantity-147", "expression": f"{depth_mm} mm", "parameterId": "depth"},
        {"btType": "BTMParameterBoolean-144", "value": True, "parameterId": "symmetric"},
    ]


def through_all_both_ways() -> list[dict]:
    return [
        {"btType": "BTMParameterEnum-145", "value": "THROUGH_ALL",
         "enumName": "BoundingType", "parameterId": "endBound"},
        {"btType": "BTMParameterBoolean-144", "value": True, "parameterId": "hasSecondDirection"},
        {"btType": "BTMParameterEnum-145", "value": "THROUGH_ALL",
         "enumName": "BoundingType", "parameterId": "secondDirectionBound"},
    ]


def add(payload: dict) -> str:
    response = request("POST", FEATURES_PATH, payload)
    status = response["featureState"]["featureStatus"]
    if status != "OK":
        raise RuntimeError(f"Feature did not regenerate successfully: {json.dumps(response)}")
    feature = response["feature"]
    print(f"{feature['name']}: {feature['featureId']}")
    return feature["featureId"]


# --- the model ------------------------------------------------------------

# Member A carries the lower half of the lap.  Its profile is drawn on Front,
# where the sketch axes map to global (X, Z) and the extrusion runs along Y.
# The two points around the concave lap corner are the 0.4 mm relief chamfer.
MEMBER_A_PROFILE = [
    (-MAIN_END, 0.0), (LAP_END, 0.0), (LAP_END, HALF_LAP),
    (-HALF, HALF_LAP), (-HALF, HEIGHT), (-MAIN_END, HEIGHT),
]


def corner_relief_loops(relief: float) -> list[list[tuple[float, float]]]:
    """One triangle at each member's concave lap corner, as two sketch regions."""
    a = [(-HALF, HALF_LAP), (-HALF + relief, HALF_LAP), (-HALF, HALF_LAP - relief)]
    return [a, mirror(a)]


def a_mortise_profile(mouth_chamfer: float) -> list[tuple[float, float]]:
    """A's mortise, with its mouth flared out at 45 degrees.

    The chamfer is folded into the pocket profile instead of being cut as a
    separate counterbore.  A counterbore leaves a step inside the pocket -- a
    visible ring that reads as a modelling accident -- while a lead-in chamfer
    does the same job, looks like what it is, and helps the tongue start in.
    """
    far, mouth = -MORTISE_BOTTOM, -HALF
    low, high = HEIGHT - MORTISE_HI, HEIGHT - MORTISE_LO
    if mouth_chamfer <= 0:
        return rectangle(far, mouth, low, high)
    return [(far, low), (mouth - mouth_chamfer, low), (mouth, low - mouth_chamfer),
            (mouth, high + mouth_chamfer), (mouth - mouth_chamfer, high), (far, high)]


A_TONGUE = rectangle(HALF, TONGUE_TIP, TONGUE_LO, TONGUE_HI)
B_TONGUE = mirror(A_TONGUE)

def wedge(x_low: float, x_high: float, z_low: float, z_high: float,
          centre: float = 0.0) -> list[tuple[float, float]]:
    """A trapezoid on Front: the wedge section, widening with z."""
    return [(centre - x_low / 2, z_low), (centre + x_low / 2, z_low),
            (centre + x_high / 2, z_high), (centre - x_high / 2, z_high)]


KEY_HOLE = wedge(HOLE_X_BOTTOM, HOLE_X_TOP, 0.0, HEIGHT)
KEY_SECTION = wedge(KEY_X_TIP, KEY_X_HEAD, KEY_PARK_Z, KEY_PARK_Z + KEY_LENGTH,
                    centre=KEY_PARK_X)


PREFIXES = tuple(f"{index:02d} ·" for index in range(1, 21))


def build(corner_relief: float = CORNER_RELIEF,
          mouth_chamfer: float = MOUTH_CHAMFER) -> None:
    step = iter(range(1, 100))

    def label(text: str) -> str:
        return f"{next(step):02d} · {text}"

    a_main = add(profile_sketch(
        label("Member A profile — 70 × 18 mm, lower half-lap 30 × 9"),
        "Front", MEMBER_A_PROFILE))
    add(extrude(label("Member A body — 24 mm wide"), a_main, "NEW", symmetric_blind(WIDTH)))

    b_main = add(profile_sketch(
        label("Member B profile — A mirrored 180° about Y"), "Front",
        mirror(MEMBER_A_PROFILE)))
    add(extrude(label("Member B body — 24 mm wide"), b_main, "NEW", symmetric_blind(WIDTH)))

    if corner_relief > 0:
        span = WIDTH - 2 * CORNER_EDGE_KEEP
        sketch = add(multi_loop_sketch(
            label(f"Lap corner relief — {corner_relief:.2f} mm, both members"),
            "Front", corner_relief_loops(corner_relief)))
        add(extrude(label(f"Cut lap corner relief — {span:.1f} mm of the 24 mm width, "
                          f"{CORNER_EDGE_KEEP:.1f} mm left sharp at each side face"),
                    sketch, "REMOVE", symmetric_blind(span)))

    a_mortise = a_mortise_profile(mouth_chamfer)
    mouth_note = (f" · {mouth_chamfer:.2f} mm mouth chamfer" if mouth_chamfer > 0
                  else " · square mouth")
    for member, mortise in (("A", a_mortise), ("B", mirror(a_mortise))):
        sketch = add(profile_sketch(
            label(f"Member {member} mortise — 5.40 × 3.10 mm{mouth_note}"), "Front", mortise))
        add(extrude(label(f"Cut {member} mortise — 8.10 mm wide"), sketch, "REMOVE",
                    symmetric_blind(2 * MORTISE_HW)))

    for member, tongue in (("A", A_TONGUE), ("B", B_TONGUE)):
        sketch = add(profile_sketch(
            label(f"Member {member} tongue — 5.00 × 2.90 mm"), "Front", tongue))
        add(extrude(label(f"Add {member} tongue — 7.90 mm wide · C = 0.20 mm"), sketch, "ADD",
                    symmetric_blind(2 * TONGUE_HW)))

    hole = add(profile_sketch(
        label(f"Key hole — {HOLE_X_BOTTOM:.2f} → {HOLE_X_TOP:.2f} mm taper"),
        "Front", KEY_HOLE))
    add(extrude(label(f"Cut key hole — {HOLE_Y:.2f} mm wide, through both laps"),
                hole, "REMOVE", symmetric_blind(HOLE_Y)))

    key = add(profile_sketch(
        label(f"Key profile — {KEY_X_TIP:.2f} → {KEY_X_HEAD:.2f} mm over {KEY_LENGTH:.2f} mm"),
        "Front", KEY_SECTION))
    add(extrude(label(f"Key — {KEY_Y:.2f} mm thick flat wedge"), key, "NEW",
                symmetric_blind(KEY_Y)))


NAME_PROPERTY = "57f3fb8efa3416c06701d60d"


def name_parts() -> None:
    """Label the three bodies.

    A rebuild resets every part to "Part N", so naming belongs here rather than
    in a separate step that is easy to forget.  The names stay ASCII because
    Onshape derives per-part export filenames from them, and the asset contract
    wants those in plain kebab-case.
    """
    wanted = {}
    for part in request("GET", f"/api/v10/parts/d/{DID}/w/{WID}/e/{EID}"):
        edges = request(
            "GET",
            f"/api/v10/parts/d/{DID}/w/{WID}/e/{EID}/partid/{part['partId']}/tessellatededges",
        )
        points = [(v["x"] * 1000, v["y"] * 1000)
                  for body in edges["bodies"] for edge in body["edges"]
                  for v in edge["vertices"]]
        low_x = min(x for x, _ in points)
        if low_x > MAIN_END:
            wanted[part["partId"]] = "Key"
        elif low_x < -MAIN_END / 2:
            wanted[part["partId"]] = "Member A (lower lap)"
        else:
            wanted[part["partId"]] = "Member B (upper lap)"
    if sorted(wanted.values()) != ["Key", "Member A (lower lap)", "Member B (upper lap)"]:
        raise RuntimeError(f"Unexpected part layout, refusing to rename: {wanted}")
    for part_id, name in wanted.items():
        request("POST", f"/api/v10/metadata/d/{DID}/w/{WID}/e/{EID}/p/{part_id}",
                {"properties": [{"propertyId": NAME_PROPERTY, "value": name}]})
        print(f"named {part_id}: {name}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--rebuild", action="store_true",
        help="delete this script's own features and build them again",
    )
    parser.add_argument(
        "--no-relief", action="store_true",
        help="build without the lap-corner chamfer and the mortise-mouth chamfer, "
             "leaving every mating corner sharp",
    )
    args = parser.parse_args()

    initial = request("GET", FEATURES_PATH)
    if args.rebuild:
        if any(not f.get("name", "").startswith(PREFIXES) for f in initial["features"]):
            raise RuntimeError(
                "Target Part Studio holds features this script did not create; "
                "refusing to delete possible user work."
            )
        for feature in reversed(initial["features"]):
            request("DELETE", FEATURES_PATH + f"/featureid/{feature['featureId']}")
        initial = request("GET", FEATURES_PATH)
    if initial["features"]:
        raise RuntimeError("Target Part Studio is not empty; refusing to append features.")

    build(corner_relief=0.0 if args.no_relief else CORNER_RELIEF,
          mouth_chamfer=0.0 if args.no_relief else MOUTH_CHAMFER)
    name_parts()

    final = request("GET", FEATURES_PATH)
    failing = [
        name for name, state in final["featureStates"].items()
        if state["featureStatus"] != "OK"
    ]
    if failing:
        raise RuntimeError(f"Unexpected failing feature states: {failing}")
    print(f"Verified {len(final['features'])} native features; all regenerated successfully.")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (KeyError, RuntimeError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        raise SystemExit(1)
